# Generated by Django 5.2.3 on 2025-06-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızilelma')], max_length=10, verbose_name='Hava Aracı Modeli')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seri Numarası')),
                ('assembly_date', models.DateTimeField(auto_now_add=True, verbose_name='Montaj Tarihi')),
                ('assembled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembled_aircrafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hava Aracı',
                'verbose_name_plural': 'Hava Araçları',
            },
        ),
    ]
