# Generated by Django 5.2.3 on 2025-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='serial_number',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Seri Numarası'),
        ),
    ]
