# Generated by Django 5.2.3 on 2025-06-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('KANAT', 'Kanat Takımı'), ('GOVDE', 'Gövde Takımı'), ('KUYRUK', 'Kuyruk Takımı'), ('AVIYONIK', 'Aviyonik Takımı'), ('MONTAJ', 'Montaj Takımı')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.team'),
        ),
    ]
